namespace dnd_character_sheet
{
    public enum EnumPrintSheetInfoTitles
    {
        Name,
        Race,
        Class,
        Level,
        Expirience,
        Abilities,
        Skills,
        Proficiencies,
        PersonalityList,
        CombatStats,
        HP,
        THP,
        AC,
        Speed,
        HitDice,
        HitDiceCount,
        DeathDices,
        Inventory,
        Traits,
        PassiveWisdom,
        ProficiencyBonus,
        Inspiration,
        Size,
        Hero
    }
}