namespace dnd_character_sheet
{
    public enum EnumInstrumentsProficienciesDND5E
    {
	    AlchemistsSupplies,
        BrewersSupplies,
        CalligraphersSupplies,
        CarpentersTools,
        CartographersTools,
        CobblersTools,
        CooksUtensils,
        GlassblowersTools,
        JewelersTools,
        LeatherworkersTools,
        MasonsTools,
        PaintersSupplies,
        PottersTools,
        SmithsTools,
        TinkersTools,
        WeaversTools,
        WoodcarversTools,
        NavigatorsTools,
        PoisonersKit,
        ThievesTools,
		DisguiseKit,
        ForgeryKit,
		Herbalism
    }
}